### ISSUE TITLE
PayPal Plus module disables complete Oxid payment error handling

### ISSUE THREAD

**Issue by FatchipRobert** [OXIDprojects/paypalplus-module#6]
Can you explain to me why your module would need to override the complete Oxid payment error handling?

In the PaymentGateway extension
https://github.com/OXIDprojects/paypalplus-module/blob/master/models/payppaypalplusoxpaymentgateway.php

you override the methods getLastError and getLastErrorNo with returning your own hardcoded error message.
This results in the Oxid shop always showing a PayPal error message when a payment was not successful.
Completely ignoring that there might be other payment modules present in the shop.

Please remove this and use the standard ways of Oxid to show your error messages when it is appropriate.

**Comment by mariolorenz** [comment]
@FatchipRobert, sorry for the answer-delay. I'll take care of the error correction and report you with the fix ...

**Comment by mariolorenz** [comment]
Hello @FatchipRobert, i´ve create a Fix-Branch:   **PayPal_Plus_module_disables_complete_Oxid_payment_error_handling** 

My solution is, that i set the Paypal-Error-Message only if a Paypal-Error exists (inside the executePayment), and remove the unecessary overload Module-Methods: getLastError, setLastError, getLastErrorNo, setLastErrorNo.

Did you´ve a test-system where you can checkout this branch and test it togehter with your other payment-modules?

**Comment by FatchipRobert** [comment]
Hello @mariolorenz,

your changes look good and seem to be working fine.
Thank you for your changes.

**Comment by mariolorenz** [comment]
fixed with version >= 3.0.9
