### ISSUE TITLE
Css only spinner

### ISSUE THREAD

**Issue by ivoba** [OXIDprojects/paypalplus-module#8]
Any objections against a css only spinner?
So we could get rid off a hard dependency on azure theme in 
https://github.com/OXIDprojects/paypalplus-module/blob/master/out/src/css/payppaypalpluswall.css#L4

**Comment by mariolorenz** [comment]
@ivoba : i´ve removed the hard coded dependency on azure theme. I´ve solved by provide the spinner file in the module-resources. It is not your prefered CSS-only solution, but in this case with the old module an alternative. PayPal works on a new Modul, that should replace this old module.
